export const FETCH_TASK = 'FETCH_TASK';
export const FETCH_TASK_SUCCESS = 'FETCH_TASK_SUCCESS';
export const FETCH_TASK_FAILED = 'FETCH_TASK_FAILED';

export const SEARCH_TASK = 'SEARCH_TASK';
export const SEARCH_TASK_SUCCESS = 'SEARCH_TASK_SUCCESS';